version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sql_data:/var/opt/mssql

  vehiclerental.api:
    build:
      context: ./VehicleRental.API
      dockerfile: Dockerfile
    image: vehiclerentalapi
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=VehicleRentalDb;User=sa;Password=${SA_PASSWORD};Encrypt=false;"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sql_data:
